In [1]:
import polars as pl
from pathlib import Path

In [2]:
DATA_GENERAL = Path("../data_general")
DATA_PERSONAL = Path("../data_personal/Spotify Extended Streaming History")
OUT_DATA = Path('../output')

In [3]:
lazy_general_df = pl.scan_parquet(DATA_GENERAL / "spotify_audio_features_*.parquet")

In [4]:
general_df = (
    lazy_general_df
    .filter(pl.col('null_response') == 0)   
    .drop('null_response')
    .collect()
)

In [5]:
general_df = general_df.rename({ 'id' : 'spotify_track_uri' })

In [6]:
display(general_df.head())

shape: (5, 16)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name       ┆ popularit ┆ duration_ ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---        ┆ y         ┆ ms        ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 2Pe9cbhOTv ┆ I dreamt   ┆ 0         ┆ 630506    ┆ … ┆ 0.816     ┆ 0.737     ┆ 0.177    ┆ 0.0299  │
│ OUTDE4bl7z ┆ you died   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zl         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 0wP732NKm8 ┆ It's Death ┆ 0         ┆ 97216     ┆ … ┆ 0.587     ┆ 0.782     ┆ 0.202    ┆ 0.36    │
│ XgXu78XLRW ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ oR         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 22L6EJdnjx ┆ Preliminar ┆ 0         ┆ 75180     ┆ … ┆ 0.923     ┆ 0.939     ┆ 0.106    ┆ 0.0362  │
│ 8oIo7GiF9h ┆ y          ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ Le         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 3a519lgQ13 ┆ Disparage  ┆ 0         ┆ 149447    ┆ … ┆ 0.78      ┆ 0.799     ┆ 0.132    ┆ 0.0634  │
│ JXNi0G73mw ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ MT         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 27yP7p2lxW ┆ Cut Down   ┆ 0         ┆ 120816    ┆ … ┆ 0.843     ┆ 0.109     ┆ 0.126    ┆ 0.187   │
│ YTtnldRN8K ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zx         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [7]:
personal_data_frames = {}
for num in range (2022,2027) :
    personal_data_frames[num] = pl.read_json(
        DATA_PERSONAL / f'Streaming_History_Audio_{num}.json',
        infer_schema_length=None  
        )

In [91]:
song_uri = '3U0UXxBIfjUsJ8RtxoxUFn'

In [92]:
stats = general_df.filter(pl.col('spotify_track_uri') == song_uri)

In [93]:
display(stats)

shape: (1, 16)
┌────────────┬──────────┬────────────┬────────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name     ┆ popularity ┆ duration_m ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---      ┆ ---        ┆ s          ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str      ┆ i64        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆          ┆            ┆ i64        ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪══════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 3U0UXxBIfj ┆ Monolith ┆ 64         ┆ 264656     ┆ … ┆ 0.000409  ┆ 0.756     ┆ 0.114    ┆ 0.799   │
│ UsJ8RtxoxU ┆          ┆            ┆            ┆   ┆           ┆           ┆          ┆         │
│ Fn         ┆          ┆            ┆            ┆   ┆           ┆           ┆          ┆         │
└────────────┴──────────┴────────────┴────────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [112]:
# Subjectife paramaters (value given in percentage according to reverens value,
#  like 0.1 is mean : from 90% to 110% of reverense value)
smart_filter = [
    (0.0001,500),
    (0.001, 50),
    (0.01, 5),
    (0.1, 0.5),
    (0.2, 0.25),
    (0.4, 0.15),
    (0.6, 0.1),
    (0.8, 0.07),
    (1, 0.05),
]

subj_params = ['danceability','energy','speechiness','acousticness','instrumentalness','liveness','valence']

cofs = {}

for param in subj_params:
    for val, cof in smart_filter:
        if stats[param][0] < val:
            cofs[param] = cof
            break

#cof_dance = 0.1
#cof_energy = 0.2 
#cof_speech = 0.2
#cof_acoustic = 0.2
#cof_instr = 0.2 
#cof_live = 0.2
#cof_valence = 0.2

# Technical paramaters (in absalute value)
cof_tempo = 5 #bbm
cof_loud = 2 #Db

#subj_features = [       
#    ( cofs, 'danceability' ),     
#    (cof_energy, 'energy'),    
#    (cof_speech,  'speechiness' ),   
#    (cof_acoustic,'acousticness') ,
#    (cof_instr, 'instrumentalness'),    
# #   (cof_live, 'liveness'),    
#    (cof_valence, 'valence'),     
#]

tech_features = [        
    (cof_loud, 'loudness' )    
]

In [113]:
print(cofs)

{'danceability': 0.1, 'energy': 0.05, 'speechiness': 0.5, 'acousticness': 50, 'instrumentalness': 0.07, 'liveness': 0.25, 'valence': 0.07}

In [114]:
conditions = []

In [115]:
# Accept subjective features

for param in subj_params:
    state = stats[param]
    cond = pl.col(param).is_between(
        state * (1 - cofs[param]),
        state * (1 + cofs[param])
    )
    conditions.append(cond)

In [116]:
# Accept techical features

for cof, state_key in tech_features:

    state = stats[state_key]
    cond = pl.col(state_key).is_between(
        state - cof,
        state + cof
    )
    conditions.append(cond)

In [118]:
if conditions:
    result = (
        general_df.lazy()
        .filter(conditions)
        .filter( (pl.col('key') == stats['key']) & (pl.col('time_signature') == stats['time_signature']) & (pl.col('mode') == stats['mode']))
        .filter( (pl.col('tempo').is_between(stats['tempo'] - cof_tempo, stats['tempo'] + cof_tempo) ) | (pl.col('tempo').is_between((stats['tempo'] - cof_tempo)/2, (stats['tempo'] + cof_tempo) / 2) ) | (pl.col('tempo').is_between((stats['tempo'] - cof_tempo)*2, (stats['tempo'] + cof_tempo)*2) ))
        .collect()
    )

In [123]:
print(len(result))
result = result.with_columns(
    pl.format("spotify:track:{}", pl.col("spotify_track_uri")).alias("spotify_track_uri")
)
display(result.head())

20

shape: (5, 16)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name       ┆ popularit ┆ duration_ ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---        ┆ y         ┆ ms        ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ spotify:tr ┆ 慟哭       ┆ 0         ┆ 251227    ┆ … ┆ 0.000048  ┆ 0.769     ┆ 0.0873   ┆ 0.819   │
│ ack:spotif ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ y:track:sp ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ Waterfall  ┆ 0         ┆ 478123    ┆ … ┆ 0.0000337 ┆ 0.762     ┆ 0.0904   ┆ 0.818   │
│ ack:spotif ┆ - Original ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ y:track:sp ┆ Mix        ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ The        ┆ 0         ┆ 586500    ┆ … ┆ 0.0000209 ┆ 0.788     ┆ 0.127    ┆ 0.787   │
│ ack:spotif ┆ Message -  ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ y:track:sp ┆ Stoned Sun ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆ Remix      ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ GR3Y       ┆ 36        ┆ 265159    ┆ … ┆ 0.000005  ┆ 0.747     ┆ 0.0939   ┆ 0.76    │
│ ack:spotif ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ y:track:sp ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ Annihilati ┆ 1         ┆ 242341    ┆ … ┆ 0.000129  ┆ 0.793     ┆ 0.0859   ┆ 0.788   │
│ ack:spotif ┆ on         ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ y:track:sp ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [120]:
file_path = OUT_DATA / f"Like '{stats['name'][0]}'.csv"
result.select('spotify_track_uri').write_csv(file_path , separator=',')