In [1]:
import polars as pl
from pathlib import Path

In [2]:
DATA_GENERAL = Path("../data_general")
DATA_PERSONAL = Path("../data_personal/Spotify Extended Streaming History")

In [3]:
general_data_frames = []
for num in range (10) :
    general_data_frames.append(pl.read_parquet(DATA_GENERAL / f'spotify_audio_features_{num}.parquet'))

In [4]:
display(general_data_frames[0].head())

shape: (5, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ id         ┆ name       ┆ popularit ┆ null_resp ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ---        ┆ ---        ┆ y         ┆ onse      ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│            ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 2Pe9cbhOTv ┆ I dreamt   ┆ 0         ┆ 0         ┆ … ┆ 0.816     ┆ 0.737     ┆ 0.177    ┆ 0.0299  │
│ OUTDE4bl7z ┆ you died   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zl         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 0wP732NKm8 ┆ It's Death ┆ 0         ┆ 0         ┆ … ┆ 0.587     ┆ 0.782     ┆ 0.202    ┆ 0.36    │
│ XgXu78XLRW ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ oR         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 22L6EJdnjx ┆ Preliminar ┆ 0         ┆ 0         ┆ … ┆ 0.923     ┆ 0.939     ┆ 0.106    ┆ 0.0362  │
│ 8oIo7GiF9h ┆ y          ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ Le         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 3a519lgQ13 ┆ Disparage  ┆ 0         ┆ 0         ┆ … ┆ 0.78      ┆ 0.799     ┆ 0.132    ┆ 0.0634  │
│ JXNi0G73mw ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ MT         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 27yP7p2lxW ┆ Cut Down   ┆ 0         ┆ 0         ┆ … ┆ 0.843     ┆ 0.109     ┆ 0.126    ┆ 0.187   │
│ YTtnldRN8K ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zx         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [5]:
personal_data_frames = {}
for num in range (2022,2027) :
    personal_data_frames[num] = pl.read_json(
        DATA_PERSONAL / f'Streaming_History_Audio_{num}.json',
        infer_schema_length=None  
        )

In [6]:
personal_data_frames[2022] =personal_data_frames[2022].with_columns(pl.col("spotify_track_uri").str.slice(14,22))

In [7]:
check_mus_id = personal_data_frames[2022]["spotify_track_uri"][0]
print(check_mus_id)

4u7EnebtmKWzUH433cf5Qv

In [8]:
#print(len(general_data_frames))
for g in range(10):
    general_data_frames[g] = general_data_frames[g].rename({ 'id' : 'spotify_track_uri' })
print(general_data_frames[0])

shape: (25_558_893, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name       ┆ popularit ┆ null_resp ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---        ┆ y         ┆ onse      ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 2Pe9cbhOTv ┆ I dreamt   ┆ 0         ┆ 0         ┆ … ┆ 0.816     ┆ 0.737     ┆ 0.177    ┆ 0.0299  │
│ OUTDE4bl7z ┆ you died   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zl         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 0wP732NKm8 ┆ It's Death ┆ 0         ┆ 0         ┆ … ┆ 0.587     ┆ 0.782     ┆ 0.202    ┆ 0.36    │
│ XgXu78XLRW ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ oR         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 22L6EJdnjx ┆ Preliminar ┆ 0         ┆ 0         ┆ … ┆ 0.923     ┆ 0.939     ┆ 0.106    ┆ 0.0362  │
│ 8oIo7GiF9h ┆ y          ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ Le         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 3a519lgQ13 ┆ Disparage  ┆ 0         ┆ 0         ┆ … ┆ 0.78      ┆ 0.799     ┆ 0.132    ┆ 0.0634  │
│ JXNi0G73mw ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ MT         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 27yP7p2lxW ┆ Cut Down   ┆ 0         ┆ 0         ┆ … ┆ 0.843     ┆ 0.109     ┆ 0.126    ┆ 0.187   │
│ YTtnldRN8K ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zx         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …       │
│ 0SDqCqvWzQ ┆ What       ┆ 1         ┆ 0         ┆ … ┆ 0.819     ┆ 0.0       ┆ 0.076    ┆ 0.137   │
│ t870CpFV2T ┆ You're     ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ tJ         ┆ Doing To   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆ Me         ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 5gWtSuvakc ┆ Necklace   ┆ 1         ┆ 0         ┆ … ┆ 0.849     ┆ 0.000198  ┆ 0.35     ┆ 0.219   │
│ UnYy21pEzy ┆ and A      ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ uP         ┆ Stone      ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 1ol5fazT5K ┆ This       ┆ 0         ┆ 0         ┆ … ┆ 0.0432    ┆ 0.000006  ┆ 0.117    ┆ 0.156   │
│ JY4dSRSMIm ┆ Life's A   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zf         ┆ Game -     ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│            ┆ Extended … ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 6QMZLZ4ew1 ┆ AUDI       ┆ 2         ┆ 0         ┆ … ┆ 0.0238    ┆ 0.0       ┆ 0.501    ┆ 0.314   │
│ SWiCAPubal ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ ti         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 2AXkG13zpn ┆ MAZDA      ┆ 0         ┆ 0         ┆ … ┆ 0.24      ┆ 0.0168    ┆ 0.121    ┆ 0.61    │
│ 8dTddrB006 ┆ MIATA      ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ kG         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [ ]:
status = False
mus_name = ''
for g in range(10):
    for url in general_data_frames[g]['spotify_track_uri']:
        if url == check_mus_id:
            status = True
            mus_name = general_data_frames[g].filter(pl.col('spotify_track_uri') == url).select(['name',])
            break
    if status :
        break

print(status, mus_name)

True shape: (1, 1)
┌─────────────────────────────────┐
│ name                            │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ Bohemian Rhapsody - Remastered… │
└─────────────────────────────────┘

# NOW LET`S FIND OUT TRACK

In [12]:
song_uri = '3U0UXxBIfjUsJ8RtxoxUFn'

In [28]:

for g in range (10):
    if song_uri in general_data_frames[g]['spotify_track_uri']:
        print(g)
        stats = general_data_frames[g].filter(pl.col('spotify_track_uri') == song_uri).select(['name','tempo','danceability','energy','loudness','speechiness','acousticness','instrumentalness','liveness','valence'])
        break

2

In [16]:
display(stats)

shape: (1, 10)
┌──────────┬─────────┬──────────────┬────────┬───┬──────────────┬─────────────┬──────────┬─────────┐
│ name     ┆ tempo   ┆ danceability ┆ energy ┆ … ┆ acousticness ┆ instrumenta ┆ liveness ┆ valence │
│ ---      ┆ ---     ┆ ---          ┆ ---    ┆   ┆ ---          ┆ lness       ┆ ---      ┆ ---     │
│ str      ┆ f64     ┆ f64          ┆ f64    ┆   ┆ f64          ┆ ---         ┆ f64      ┆ f64     │
│          ┆         ┆              ┆        ┆   ┆              ┆ f64         ┆          ┆         │
╞══════════╪═════════╪══════════════╪════════╪═══╪══════════════╪═════════════╪══════════╪═════════╡
│ Monolith ┆ 142.013 ┆ 0.508        ┆ 0.952  ┆ … ┆ 0.000409     ┆ 0.756       ┆ 0.114    ┆ 0.799   │
└──────────┴─────────┴──────────────┴────────┴───┴──────────────┴─────────────┴──────────┴─────────┘

# I have priority on the  energy, instrumentalness and valence

In [ ]:
energy = (float(stats['energy'][0]) - 0.02 , float(stats['energy'][0]) + 0.02 )
instr = (float(stats['instrumentalness'][0]) - 0.02 , float(stats['instrumentalness'][0]) + 0.02 )
valence = (float(stats['valence'][0]) - 0.02 , float(stats['valence'][0]) + 0.02 )

print(energy)

(0.9319999999999999, 0.972)

In [29]:
result = general_data_frames[2].filter((pl.col('energy').is_between(energy[0], energy[1])) & 
                                        (pl.col('instrumentalness').is_between(instr[0], instr[1])) &
                                        (pl.col('valence').is_between(valence[0], valence[1]))
                                        )

In [30]:
display(result)

shape: (583, 17)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name       ┆ popularit ┆ null_resp ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---        ┆ y         ┆ onse      ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 04A1SwAIRo ┆ High Speed ┆ 0         ┆ 0         ┆ … ┆ 0.146     ┆ 0.764     ┆ 0.171    ┆ 0.779   │
│ p8g5m26Ev9 ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ l4         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 429WhcRrxH ┆ Drugs      ┆ 0         ┆ 0         ┆ … ┆ 0.00132   ┆ 0.754     ┆ 0.0549   ┆ 0.781   │
│ nUXmhwcuRi ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ Kd         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 5QJkaoDwDn ┆ Sunset     ┆ 0         ┆ 0         ┆ … ┆ 0.0942    ┆ 0.751     ┆ 0.0925   ┆ 0.786   │
│ 6t7FByv9XD ┆ Overdrive  ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ P5         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 2mAPoAdGe6 ┆ Needle     ┆ 0         ┆ 0         ┆ … ┆ 0.0144    ┆ 0.776     ┆ 0.397    ┆ 0.779   │
│ Bdo92ZC0i2 ┆ Nose       ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 9D         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 7fR7Lxi5ZP ┆ JING JANAI ┆ 2         ┆ 0         ┆ … ┆ 0.000351  ┆ 0.739     ┆ 0.0801   ┆ 0.795   │
│ bZjsiKk5kg ┆ JONG KA    ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ qD         ┆ JINGIEID   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …       │
│ 5uJjwl8WF1 ┆ Alley's    ┆ 0         ┆ 0         ┆ … ┆ 0.00271   ┆ 0.755     ┆ 0.24     ┆ 0.795   │
│ nSPiNNye3n ┆ Ode        ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 80         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 5OY9wvkAIj ┆ Get Your   ┆ 0         ┆ 0         ┆ … ┆ 0.000264  ┆ 0.762     ┆ 0.342    ┆ 0.802   │
│ TQb3W2AUEJ ┆ Money      ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 5k         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 1aAoAfhXL8 ┆ The Dance  ┆ 0         ┆ 0         ┆ … ┆ 0.1       ┆ 0.757     ┆ 0.211    ┆ 0.799   │
│ Hgnj9JklKk ┆ That Never ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ wl         ┆ Ends       ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 03dyJOQ97H ┆ Space      ┆ 0         ┆ 0         ┆ … ┆ 0.417     ┆ 0.772     ┆ 0.069    ┆ 0.788   │
│ DzixwErR6Y ┆ Cowboy     ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ Zy         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 7qNTulbqRM ┆ Burden     ┆ 0         ┆ 0         ┆ … ┆ 0.0281    ┆ 0.768     ┆ 0.105    ┆ 0.809   │
│ Wnrqr2cuxB ┆ Eternal    ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ Fr         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘