In [3]:
import polars as pl
from pathlib import Path

In [4]:
DATA_GENERAL = Path("../data_general")
DATA_PERSONAL = Path("../data_personal/Spotify Extended Streaming History")
OUT_DATA = Path('../output')

In [5]:
lazy_general_df = pl.scan_parquet(DATA_GENERAL / "spotify_audio_features_*.parquet")

In [6]:
general_df = (
    lazy_general_df
    .filter(pl.col('null_response') == 0)   
    .drop('null_response')
    .collect()
)

In [7]:
general_df = general_df.rename({ 'id' : 'spotify_track_uri' })

In [8]:
display(general_df.head())

shape: (5, 16)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name       ┆ popularit ┆ duration_ ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---        ┆ y         ┆ ms        ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 2Pe9cbhOTv ┆ I dreamt   ┆ 0         ┆ 630506    ┆ … ┆ 0.816     ┆ 0.737     ┆ 0.177    ┆ 0.0299  │
│ OUTDE4bl7z ┆ you died   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zl         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 0wP732NKm8 ┆ It's Death ┆ 0         ┆ 97216     ┆ … ┆ 0.587     ┆ 0.782     ┆ 0.202    ┆ 0.36    │
│ XgXu78XLRW ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ oR         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 22L6EJdnjx ┆ Preliminar ┆ 0         ┆ 75180     ┆ … ┆ 0.923     ┆ 0.939     ┆ 0.106    ┆ 0.0362  │
│ 8oIo7GiF9h ┆ y          ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ Le         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 3a519lgQ13 ┆ Disparage  ┆ 0         ┆ 149447    ┆ … ┆ 0.78      ┆ 0.799     ┆ 0.132    ┆ 0.0634  │
│ JXNi0G73mw ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ MT         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 27yP7p2lxW ┆ Cut Down   ┆ 0         ┆ 120816    ┆ … ┆ 0.843     ┆ 0.109     ┆ 0.126    ┆ 0.187   │
│ YTtnldRN8K ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zx         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [9]:
personal_data_frames = {}
for num in range (2022,2027) :
    personal_data_frames[num] = pl.read_json(
        DATA_PERSONAL / f'Streaming_History_Audio_{num}.json',
        infer_schema_length=None  
        )

In [23]:
song_uri = '39tEggsuFc41pIFmajsWb8'

In [24]:
stats = general_df.filter(pl.col('spotify_track_uri') == song_uri)

In [25]:
display(stats)

shape: (1, 16)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name       ┆ popularit ┆ duration_ ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---        ┆ y         ┆ ms        ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 39tEggsuFc ┆ Песня крас ┆ 34        ┆ 154587    ┆ … ┆ 0.0000477 ┆ 0.199     ┆ 0.29     ┆ 0.724   │
│ 41pIFmajsW ┆ ноармейца  ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ b8         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

# I have priority on the  energy, instrumentalness and valence

In [28]:
cof_tempo = 0.1
cof_dance = 0.2
cof_energy = 0.1 
cof_loud = None
cof_speech = None
cof_acoustic = None
cof_instr = 0.2 
cof_live = 0.05
cof_valence = 0.1

features = [ 
    (cof_tempo, 'tempo') ,       
    ( cof_dance, 'danceability' ),     
    (cof_energy, 'energy'),    
    (cof_loud, 'loudness' ),    
    (cof_speech,  'speechiness' ),   
    (cof_acoustic,'acousticness') ,
    (cof_instr, 'instrumentalness'),    
    (cof_live, 'liveness'),    
    (cof_valence, 'valence'),     
]

In [29]:
conditions = []
for cof, state_key in features:
    if cof:
        state = stats[state_key]
        cond = pl.col(state_key).is_between(
            state * (1 - cof),
            state * (1 + cof)
        )
        conditions.append(cond)

In [30]:
if conditions:
    result = (
        general_df.lazy()
        .filter(conditions)
        .collect()
    )

In [31]:
print(len(result))
result = result.with_columns(
    pl.format("spotify:track:{}", pl.col("spotify_track_uri")).alias("spotify_track_uri")
)
display(result)

106

shape: (106, 16)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name       ┆ popularit ┆ duration_ ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---        ┆ y         ┆ ms        ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ spotify:tr ┆ Imposter   ┆ 0         ┆ 203408    ┆ … ┆ 0.000558  ┆ 0.18      ┆ 0.297    ┆ 0.751   │
│ ack:3SaLm6 ┆ Syndrome   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ z51350Oy4S ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ Passion    ┆ 0         ┆ 305862    ┆ … ┆ 0.00361   ┆ 0.163     ┆ 0.294    ┆ 0.693   │
│ ack:6zP3ml ┆ reverse    ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ OLoi4uYIbS ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ Aag Budh   ┆ 0         ┆ 917813    ┆ … ┆ 0.69      ┆ 0.202     ┆ 0.278    ┆ 0.792   │
│ ack:5h75tN ┆ Ko Chhod   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ QtnW6czUIL ┆ De         ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ Like Love  ┆ 0         ┆ 146256    ┆ … ┆ 0.000004  ┆ 0.185     ┆ 0.285    ┆ 0.668   │
│ ack:0n1hMw ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ F8Ld590iQY ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ We Never   ┆ 0         ┆ 173507    ┆ … ┆ 0.000118  ┆ 0.18      ┆ 0.294    ┆ 0.654   │
│ ack:2l5GAo ┆ Wanted     ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ AQnKxINoRI ┆ This       ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …       │
│ spotify:tr ┆ Morning    ┆ 0         ┆ 199827    ┆ … ┆ 0.00337   ┆ 0.197     ┆ 0.286    ┆ 0.764   │
│ ack:5UsoPZ ┆ Train -    ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ RJ5P1ZrQty ┆ Single     ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆ Version    ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ Desorden   ┆ 0         ┆ 150576    ┆ … ┆ 0.346     ┆ 0.183     ┆ 0.299    ┆ 0.656   │
│ ack:05gPLr ┆ Social     ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ JRmXDtpP1x ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ The        ┆ 2         ┆ 148267    ┆ … ┆ 0.435     ┆ 0.179     ┆ 0.279    ┆ 0.686   │
│ ack:05iZHI ┆ Hollywood  ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ pyCGalKbJ1 ┆ Scene      ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ Thin Ice   ┆ 0         ┆ 215133    ┆ … ┆ 0.5       ┆ 0.181     ┆ 0.287    ┆ 0.76    │
│ ack:2qKocL ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 5dbXM0540V ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ Песня крас ┆ 34        ┆ 154587    ┆ … ┆ 0.0000477 ┆ 0.199     ┆ 0.29     ┆ 0.724   │
│ ack:39tEgg ┆ ноармейца  ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ suFc41pIFm ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [32]:
file_path = OUT_DATA / f"Like '{stats['name'][0]}'.csv"
result.select('spotify_track_uri').write_csv(file_path , separator=',')