In [2]:
import polars as pl
from pathlib import Path

In [3]:
DATA_GENERAL = Path("../data_general")
DATA_PERSONAL = Path("../data_personal/Spotify Extended Streaming History")
OUT_DATA = Path('../output')

In [4]:
lazy_general_df = pl.scan_parquet(DATA_GENERAL / "spotify_audio_features_*.parquet")

In [5]:
general_df = (
    lazy_general_df
    .filter(pl.col('null_response') == 0)   
    .drop('null_response')
    .collect()
)

In [6]:
general_df = general_df.rename({ 'id' : 'spotify_track_uri' })

In [7]:
display(general_df.head())

shape: (5, 16)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name       ┆ popularit ┆ duration_ ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---        ┆ y         ┆ ms        ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ 2Pe9cbhOTv ┆ I dreamt   ┆ 0         ┆ 630506    ┆ … ┆ 0.816     ┆ 0.737     ┆ 0.177    ┆ 0.0299  │
│ OUTDE4bl7z ┆ you died   ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zl         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 0wP732NKm8 ┆ It's Death ┆ 0         ┆ 97216     ┆ … ┆ 0.587     ┆ 0.782     ┆ 0.202    ┆ 0.36    │
│ XgXu78XLRW ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ oR         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 22L6EJdnjx ┆ Preliminar ┆ 0         ┆ 75180     ┆ … ┆ 0.923     ┆ 0.939     ┆ 0.106    ┆ 0.0362  │
│ 8oIo7GiF9h ┆ y          ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ Le         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 3a519lgQ13 ┆ Disparage  ┆ 0         ┆ 149447    ┆ … ┆ 0.78      ┆ 0.799     ┆ 0.132    ┆ 0.0634  │
│ JXNi0G73mw ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ MT         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ 27yP7p2lxW ┆ Cut Down   ┆ 0         ┆ 120816    ┆ … ┆ 0.843     ┆ 0.109     ┆ 0.126    ┆ 0.187   │
│ YTtnldRN8K ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ zx         ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [8]:
personal_data_frames = {}
for num in range (2022,2027) :
    personal_data_frames[num] = pl.read_json(
        DATA_PERSONAL / f'Streaming_History_Audio_{num}.json',
        infer_schema_length=None  
        )

In [9]:
song_uri = '5v3Dv4UlDOGaXlvphFpkIX'

In [10]:
stats = general_df.filter(pl.col('spotify_track_uri') == song_uri)

In [11]:
display(stats)

shape: (1, 16)
┌────────────┬────────┬────────────┬────────────┬───┬────────────┬────────────┬──────────┬─────────┐
│ spotify_tr ┆ name   ┆ popularity ┆ duration_m ┆ … ┆ acousticne ┆ instrument ┆ liveness ┆ valence │
│ ack_uri    ┆ ---    ┆ ---        ┆ s          ┆   ┆ ss         ┆ alness     ┆ ---      ┆ ---     │
│ ---        ┆ str    ┆ i64        ┆ ---        ┆   ┆ ---        ┆ ---        ┆ f64      ┆ f64     │
│ str        ┆        ┆            ┆ i64        ┆   ┆ f64        ┆ f64        ┆          ┆         │
╞════════════╪════════╪════════════╪════════════╪═══╪════════════╪════════════╪══════════╪═════════╡
│ 5v3Dv4UlDO ┆ Hello  ┆ 56         ┆ 208000     ┆ … ┆ 0.000171   ┆ 0.111      ┆ 0.153    ┆ 0.227   │
│ GaXlvphFpk ┆ Juliet ┆            ┆            ┆   ┆            ┆            ┆          ┆         │
│ IX         ┆        ┆            ┆            ┆   ┆            ┆            ┆          ┆         │
└────────────┴────────┴────────────┴────────────┴───┴────────────┴────────────┴──────────┴─────────┘

In [12]:
# Subjectife paramaters (value given in percentage according to reverens value,
#  like 0.1 is mean : from 90% to 110% of reverense value)
cof_dance = 0.2
cof_energy = 0.2 
cof_speech = 0.2
cof_acoustic = 0.2
cof_instr = 0.2 
cof_live = 0.2
cof_valence = 0.2

# Technical paramaters (in absalute value)
cof_ts = 0
cof_key = 0
cof_mod = 0 
cof_tempo = 2 #bbm
cof_loud = 1 #Db

subj_features = [       
    ( cof_dance, 'danceability' ),     
    (cof_energy, 'energy'),    
    (cof_speech,  'speechiness' ),   
    (cof_acoustic,'acousticness') ,
    (cof_instr, 'instrumentalness'),    
    (cof_live, 'liveness'),    
    (cof_valence, 'valence'),     
]

tech_features = [ 
    (cof_tempo, 'tempo') ,         
    (cof_loud, 'loudness' ),    
    (cof_ts,  'time_signature' ),   
    (cof_key,'key') ,
    (cof_mod, 'mode'),     
]

In [13]:
conditions = []

In [14]:
# Accept subjective features

for cof, state_key in subj_features:
    if cof:
        state = stats[state_key]
        cond = pl.col(state_key).is_between(
            state * (1 - cof),
            state * (1 + cof)
        )
        conditions.append(cond)

In [15]:
# Accept techical features

for cof, state_key in tech_features:
    if cof:
        state = stats[state_key]
        cond = pl.col(state_key).is_between(
            state - cof,
            state + cof
        )
        conditions.append(cond)

In [16]:
if conditions:
    result = (
        general_df.lazy()
        .filter(conditions)
        .collect()
    )

In [17]:
print(len(result))
result = result.with_columns(
    pl.format("spotify:track:{}", pl.col("spotify_track_uri")).alias("spotify_track_uri")
)
display(result.head())

3

shape: (3, 16)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬─────────┐
│ spotify_tr ┆ name       ┆ popularit ┆ duration_ ┆ … ┆ acousticn ┆ instrumen ┆ liveness ┆ valence │
│ ack_uri    ┆ ---        ┆ y         ┆ ms        ┆   ┆ ess       ┆ talness   ┆ ---      ┆ ---     │
│ ---        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ f64      ┆ f64     │
│ str        ┆            ┆ i64       ┆ i64       ┆   ┆ f64       ┆ f64       ┆          ┆         │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═════════╡
│ spotify:tr ┆ North of   ┆ 0         ┆ 310187    ┆ … ┆ 0.000188  ┆ 0.091     ┆ 0.147    ┆ 0.222   │
│ ack:6dJXKU ┆ Nowhere    ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ EdEweErmQj ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ Hello      ┆ 34        ┆ 208000    ┆ … ┆ 0.00017   ┆ 0.114     ┆ 0.146    ┆ 0.212   │
│ ack:6DBP4f ┆ Juliet     ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ IvKFRIshJr ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ spotify:tr ┆ Hello      ┆ 56        ┆ 208000    ┆ … ┆ 0.000171  ┆ 0.111     ┆ 0.153    ┆ 0.227   │
│ ack:5v3Dv4 ┆ Juliet     ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ UlDOGaXlvp ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
│ …          ┆            ┆           ┆           ┆   ┆           ┆           ┆          ┆         │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴─────────┘

In [18]:
file_path = OUT_DATA / f"Like '{stats['name'][0]}'.csv"
result.select('spotify_track_uri').write_csv(file_path , separator=',')